#spring.security.user.name=zhangsan
#spring.security.user.password=123
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/studymysql?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
  type-aliases-package: com.kong.pojo
  mapper-locations: classpath:mapper/*.xml
